services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: school
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s